version: "2"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: pgreqlog
      POSTGRES_USER: pgreqlog
      POSTGRES_DB: pgreqlog
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql
  reqlog:  
    build:
        context: .
        dockerfile: docker
        args:
          - application=reqlog
          - DOCKER_BASE=reqlog_base
          - build=1
          - web_app_name="Req Log (in Docker), own instance"
          - server_secret=123
          - cookie_sign_secret=456
          - token_ttl_secs=1600
          - token_recreate_before_secs=600
          - solution_name=ReqLog
          - instance_owner_name="Umbrella corporation"
          - webappname="ReqLog (own instance)"
          - app_host=localhost
          - database_connection_string=postgresql+psycopg2://pgreqlog:pgreqlog@postgres/pgreqlog
          - app_produce_sql_echo=false
    restart: always
    ports:
      - 9000:80
    tty: true
    depends_on:
      - postgres